### ISSUE TITLE
Remove dependence on underscore

### ISSUE THREAD

**Issue by crertel** [troygoode/node-require-directory#15]
Would you be interested in a pull request that removes the dependency on underscore?

We only use:
* `_.defaults`
* `_.isFunction`
* `_.isString`

**Comment by noor** [comment]
I found underscore.js dependency trivial, so I removed it and bumped the version here:
https://github.com/noor/node-require-directory/commit/f9a024e1b5142986eb4602dc6ea1aa1262ddb783

**Comment by crertel** [comment]
Thank you! I'm sorry I didn't get to it--was swamped at work. :(

**Comment by noor** [comment]
No worries :)

We all are... aren't we?!

**Comment by troygoode** [comment]
published to npm as 2.1.0
