### ISSUE TITLE
Can't support webpack!

### ISSUE THREAD

**Issue by weineel** [troygoode/node-require-directory#34]
Will the support of webpack be added?

**Comment by danog** [comment]
That would be really nice, this lib breaks packages that require it, if using webpack.

**Comment by solognt** [comment]
You can use require.context to get the same behaviour:
```
let context = require.context('../some/directory', false, /onlyinclude.js$/);
context.keys().forEach(filename => {
	let obj = context(filename);
	obj.someFuntion();
});
```
This works with webpack.

**Comment by NathanielHill** [comment]
For anyone else looking for a solution for webpack, you can use this babel plugin:

https://github.com/vihanb/babel-plugin-wildcard

Benefit is it's all done compile-time :tada: 
Works great for me :+1:
